name: Build and Test

on:
  pull_request:
    branches:
      - v4
  push:
    branches:
      - v4
  workflow_dispatch:

jobs:
  build-and-test:
    if: ${{ github.repository == 'jackyzha0/quartz' }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    steps:
<<<<<<< HEAD
<<<<<<< HEAD
      - uses: actions/checkout@v5
=======
      - uses: actions/checkout@v4
>>>>>>> 02f2423 (Initial commit)
=======
      - uses: actions/checkout@v4
>>>>>>> 18d4681c3fa99dd2d68f2b95767544223dcd8dfb
        with:
          fetch-depth: 0

      - name: Setup Node
<<<<<<< HEAD
<<<<<<< HEAD
        uses: actions/setup-node@v5
        with:
          node-version: 22
=======
        uses: actions/setup-node@v4
        with:
          node-version: 20
>>>>>>> 02f2423 (Initial commit)
=======
        uses: actions/setup-node@v4
        with:
          node-version: 20
>>>>>>> 18d4681c3fa99dd2d68f2b95767544223dcd8dfb

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: npm ci

      - name: Check types and style
        run: npm run check

      - name: Test
        run: npm test

      - name: Ensure Quartz builds, check bundle info
<<<<<<< HEAD
<<<<<<< HEAD
        run: npx quartz build --bundleInfo -d docs
=======
        run: npx quartz build --bundleInfo
>>>>>>> 02f2423 (Initial commit)
=======
        run: npx quartz build --bundleInfo
>>>>>>> 18d4681c3fa99dd2d68f2b95767544223dcd8dfb

  publish-tag:
    if: ${{ github.repository == 'jackyzha0/quartz' && github.ref == 'refs/heads/v4' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
<<<<<<< HEAD
<<<<<<< HEAD
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 22
=======
=======
>>>>>>> 18d4681c3fa99dd2d68f2b95767544223dcd8dfb
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
<<<<<<< HEAD
>>>>>>> 02f2423 (Initial commit)
=======
>>>>>>> 18d4681c3fa99dd2d68f2b95767544223dcd8dfb
      - name: Get package version
        run: node -p -e '`PACKAGE_VERSION=${require("./package.json").version}`' >> $GITHUB_ENV
      - name: Create release tag
        uses: pkgdeps/git-tag-action@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_repo: ${{ github.repository }}
          version: ${{ env.PACKAGE_VERSION }}
          git_commit_sha: ${{ github.sha }}
          git_tag_prefix: "v"
